### PR TITLE
Fixes

### LINKED ISSUE #17: Version comparison fails
The implementation of the version comparison of the `Constraint` will fails when using a sub class of `Constraint`.

For instance if a 3rd party code still uses the `Composer\Package\LinkConstraint\VersionConstraint` class which is a subclass. It will fail because the `$provider->version` property is private and is only accessible from the `Constraint` class itself.

https://github.com/composer/semver/blob/5356567e1c08e10998aac6e385a38c7a8f163437/src/Constraint/Constraint.php#L159

Related issue contao-community-alliance/composer-plugin/issues/44.

### PR DESCRIPTION
**Pull request by Seldaek**
Salvaged some tests and changes from #18 and then fixed #17 and updated changelog and all so I think it's ready for a 1.1 but please review :)

### CODE REVIEW

File: src/Constraint/Constraint.php [hunk 1]
```diff
@@ -55,10 +55,49 @@ class Constraint extends AbstractConstraint
...
+
+    /**
+     * @param ConstraintInterface $provider
+     *
+     * @return bool
+     */
+    public function matches(ConstraintInterface $provider)
+    {
+        if ($provider instanceof $this) {
+            // see note at bottom of this class declaration
```
Comment (alcohol) [inline src/Constraint/Constraint.php]: What note?

Comment (Seldaek) [inline src/Constraint/Constraint.php]: The note that says copy pasting stuff is evil :p Fixed
